#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=arc-local-constants.sh
source "$SCRIPT_DIR/arc-local-constants.sh"

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "ERROR: required command not found: $1"
    exit 1
  fi
}

require_cmd forge
require_cmd cast
require_cmd curl

echo "==> Checking Anvil at $ANVIL_RPC_URL"
if ! curl -sf -X POST "$ANVIL_RPC_URL" -H 'Content-Type: application/json' \
  -d '{"jsonrpc":"2.0","method":"eth_chainId","id":1}' >/dev/null; then
  echo "ERROR: no JSON-RPC at $ANVIL_RPC_URL — start Anvil first (e.g. scripts/run-local-arc-demo.sh)."
  exit 1
fi

BC_DIR="$REPO_ROOT/blockchain"
if [[ ! -f "$BC_DIR/foundry.toml" ]]; then
  echo "ERROR: blockchain/foundry.toml not found"
  exit 1
fi

if [[ ! -d "$BC_DIR/lib/forge-std" ]]; then
  echo "ERROR: Foundry libs missing. Run: cd blockchain && ./install-deps.sh"
  exit 1
fi

mkdir -p "$REPO_ROOT/.local-demo"

echo "==> forge build"
(cd "$BC_DIR" && forge build)

echo "==> Deploy MockUSDC + SNAPSpender (broadcast)"
export PRIVATE_KEY="$ANVIL_ACCOUNT_0_PRIVATE_KEY"
(cd "$BC_DIR" && forge script script/Deploy.s.sol:DeployScript \
  --rpc-url "$ANVIL_RPC_URL" \
  --broadcast \
  2>&1 | tee "$REPO_ROOT/.local-demo/last-deploy.log")

RUN_JSON=""
if [[ -f "$BC_DIR/broadcast/Deploy.s.sol/31337/run-latest.json" ]]; then
  RUN_JSON="$BC_DIR/broadcast/Deploy.s.sol/31337/run-latest.json"
else
  RUN_JSON="$(find "$BC_DIR/broadcast/Deploy.s.sol" -name run-latest.json 2>/dev/null | head -1 || true)"
fi

if [[ -z "$RUN_JSON" || ! -f "$RUN_JSON" ]]; then
  echo "ERROR: could not find broadcast run-latest.json under broadcast/Deploy.s.sol/"
  exit 1
fi

echo "==> Parsing deployment from $RUN_JSON"

parse_addresses() {
  local json="$1"
  if command -v jq >/dev/null 2>&1; then
    USDC_ADDRESS="$(jq -r '.transactions[] | select(.contractName=="MockUSDC") | .contractAddress' "$json" | head -1)"
    SNAP_SPENDER_ADDRESS="$(jq -r '.transactions[] | select(.contractName=="SNAPSpender") | .contractAddress' "$json" | head -1)"
  elif command -v python3 >/dev/null 2>&1; then
    local _lines
    _lines="$(python3 -c '
import json, sys
with open(sys.argv[1]) as f:
    d = json.load(f)
usdc = sp = None
for t in d.get("transactions", []):
    cn = t.get("contractName")
    if cn == "MockUSDC":
        usdc = t.get("contractAddress")
    if cn == "SNAPSpender":
        sp = t.get("contractAddress")
print(usdc or "")
print(sp or "")
' "$json")"
    USDC_ADDRESS="$(echo "$_lines" | sed -n '1p')"
    SNAP_SPENDER_ADDRESS="$(echo "$_lines" | sed -n '2p')"
  else
    echo "ERROR: need jq or python3 to parse deployment JSON"
    exit 1
  fi
}

USDC_ADDRESS=""
SNAP_SPENDER_ADDRESS=""
parse_addresses "$RUN_JSON"

if [[ -z "$USDC_ADDRESS" || -z "$SNAP_SPENDER_ADDRESS" || "$USDC_ADDRESS" == "null" ]]; then
  echo "ERROR: failed to parse contract addresses (MockUSDC / SNAPSpender)."
  exit 1
fi

cat > "$REPO_ROOT/.local-demo/contracts.env" <<EOF
# Generated by deploy-local-contracts.sh — local Anvil only
SNAP_SPENDER_ADDRESS=$SNAP_SPENDER_ADDRESS
USDC_ADDRESS=$USDC_ADDRESS
ADMIN_ADDRESS=$ANVIL_ACCOUNT_0_ADDRESS
RPC_URL=$ANVIL_RPC_URL
DEMO_USER_ADDRESS=$ANVIL_ACCOUNT_1_ADDRESS
DEMO_MERCHANT_ADDRESS=$ANVIL_ACCOUNT_2_ADDRESS
EOF

echo "==> Wrote $REPO_ROOT/.local-demo/contracts.env"
echo "    SNAP_SPENDER_ADDRESS=$SNAP_SPENDER_ADDRESS"
echo "    USDC_ADDRESS=$USDC_ADDRESS"
echo "    ADMIN_ADDRESS=$ANVIL_ACCOUNT_0_ADDRESS"
