#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=arc-local-constants.sh
source "$SCRIPT_DIR/arc-local-constants.sh"

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "ERROR: required command not found: $1"
    exit 1
  fi
}

require_cmd node
require_cmd npm

CONTRACTS_ENV="$REPO_ROOT/.local-demo/contracts.env"
if [[ ! -f "$CONTRACTS_ENV" ]]; then
  echo "ERROR: $CONTRACTS_ENV missing — run scripts/deploy-local-contracts.sh first."
  exit 1
fi

# shellcheck source=/dev/null
set -a
source "$CONTRACTS_ENV"
set +a

BACKEND_DIR="$REPO_ROOT/backend"
if [[ ! -f "$BACKEND_DIR/package.json" ]]; then
  echo "ERROR: backend/package.json not found"
  exit 1
fi

if [[ ! -d "$BACKEND_DIR/node_modules" ]]; then
  echo "==> npm install (backend)"
  (cd "$BACKEND_DIR" && npm install)
fi

PORT="${PORT:-3000}"

echo "==> Writing backend/.env for local Anvil (operator = Anvil account #0, disposable)"
if [[ ! -f "$BACKEND_DIR/.env.local.example" ]]; then
  echo "WARN: backend/.env.local.example missing — continuing"
fi
cat > "$BACKEND_DIR/.env" <<EOF
# Generated by scripts/run-local-backend.sh — LOCAL ANVIL ONLY
# Field meanings: see backend/.env.local.example
RPC_URL=${RPC_URL:-$ANVIL_RPC_URL}
PORT=$PORT
OPERATOR_PRIVATE_KEY=$ANVIL_ACCOUNT_0_PRIVATE_KEY
SNAP_SPENDER_ADDRESS=$SNAP_SPENDER_ADDRESS
USDC_ADDRESS=$USDC_ADDRESS
EOF

mkdir -p "$REPO_ROOT/.local-demo"
echo "==> Starting backend on http://127.0.0.1:$PORT (background)"
(cd "$BACKEND_DIR" && node src/index.js >> "$REPO_ROOT/.local-demo/backend.log" 2>&1) &
echo $! > "$REPO_ROOT/.local-demo/backend.pid"
echo "    PID $(cat "$REPO_ROOT/.local-demo/backend.pid") — log: .local-demo/backend.log"
